"""init

Revision ID: dbd05dd3520f
Revises: 
Create Date: 2025-10-16 10:51:08.371317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd05dd3520f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('invite_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_invite_code'), ['invite_code'], unique=True)

    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('team', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_player_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('board_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_post_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_board_post_league_id'), ['league_id'], unique=False)

    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'league_id', name='uq_user_league')
    )
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_user_id'), ['user_id'], unique=False)

    op.create_table('roster_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'league_id', 'player_id', name='uq_user_league_player')
    )
    with op.batch_alter_table('roster_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roster_entry_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roster_entry_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roster_entry_user_id'), ['user_id'], unique=False)

    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.Integer(), nullable=False),
    sa.Column('offered_player_ids', sa.Text(), nullable=False),
    sa.Column('requested_player_ids', sa.Text(), nullable=False),
    sa.Column('numeric_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['proposer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    with op.batch_alter_table('roster_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roster_entry_user_id'))
        batch_op.drop_index(batch_op.f('ix_roster_entry_player_id'))
        batch_op.drop_index(batch_op.f('ix_roster_entry_league_id'))

    op.drop_table('roster_entry')
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_membership_league_id'))

    op.drop_table('membership')
    with op.batch_alter_table('board_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_post_league_id'))
        batch_op.drop_index(batch_op.f('ix_board_post_author_id'))

    op.drop_table('board_post')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_name'))
        batch_op.drop_index(batch_op.f('ix_player_external_id'))

    op.drop_table('player')
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_invite_code'))

    op.drop_table('league')
    # ### end Alembic commands ###
